### ISSUE TITLE
Sign in via Google

### ISSUE THREAD

**Issue by aurusapps** [AppWerft/Ti.Firebase#1]
Hi,

Are there any plans to implement Sign-in via Google functionality?

**Comment by AppWerft** [comment]
Yes

**Comment by aurusapps** [comment]
Thats great, thank you for the module so far!
Would you have an ETA?

I could attempt helping out on the sign-in via Google on the iOS branch in the meanwhile then.

**Comment by aurusapps** [comment]
For any one else looking for google sign-in, Hans from Appcelerator just added one for iOS: https://github.com/hansemannn/ti.googlesignin

**Comment by AppWerft** [comment]
Next week.

**Comment by aurusapps** [comment]
That would be so great, thank you!

I'm almost through with mine (stuck on some weird errors), if i finish sooner, will share the code.

**Comment by aurusapps** [comment]
Thanks @AppWerft for creating the google signin in as a separate repository
https://github.com/AppWerft/Ti.GoogleSignIn
